general:
  device: cpu
  seed: 42
  save_output: true
  save_adv_example: false
  enable_incomplete_verification: true
model:
  name: custom
  onnx_path: /gpfs/radev/scratch/xu_hua/mj756/course_proj/NNV/verification_bounds/cycle_model.onnx
  input_shape:
  - -1
  - 1
specification:
  vnnlib_path: /gpfs/radev/scratch/xu_hua/mj756/course_proj/NNV/verification_bounds/small_range_tests/monotonicity_range_100_150.vnnlib
solver:
  bound_prop_method: alpha-crown
  batch_size: 2048
attack:
  pgd_order: skip
